#!/bin/bash
# Generate backend.hcl files for all environments from backend Terraform outputs
# Usage: ./generate-backend-configs.sh

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "========================================"
echo "  Backend Configuration Generator"
echo "========================================"
echo ""

# Check if we're in the right directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_ROOT="$(dirname "$SCRIPT_DIR")"
BACKEND_DIR="${TERRAFORM_ROOT}/backend"

if [ ! -d "$BACKEND_DIR" ]; then
    echo -e "${RED}Error: Backend directory not found at ${BACKEND_DIR}${NC}"
    exit 1
fi

# Navigate to backend directory
cd "$BACKEND_DIR"

# Check if backend is deployed
if [ ! -f "terraform.tfstate" ]; then
    echo -e "${RED}Error: Backend not deployed yet!${NC}"
    echo "Please run: cd ${BACKEND_DIR} && terraform init && terraform apply"
    exit 1
fi

# Get backend configuration from Terraform outputs
echo "Fetching backend configuration from Terraform outputs..."
BUCKET_NAME=$(terraform output -raw state_bucket_name 2>/dev/null)
TABLE_NAME=$(terraform output -raw state_lock_table_name 2>/dev/null)
REGION=$(terraform output -raw state_bucket_region 2>/dev/null)

if [ -z "$BUCKET_NAME" ] || [ -z "$TABLE_NAME" ] || [ -z "$REGION" ]; then
    echo -e "${RED}Error: Could not retrieve backend outputs${NC}"
    echo "Make sure the backend has been applied: terraform apply"
    exit 1
fi

echo -e "${GREEN}✓${NC} Backend bucket: ${BUCKET_NAME}"
echo -e "${GREEN}✓${NC} Lock table: ${TABLE_NAME}"
echo -e "${GREEN}✓${NC} Region: ${REGION}"
echo ""

# Function to generate backend.hcl file
generate_backend_config() {
    local ENV=$1
    local ENV_DIR="${TERRAFORM_ROOT}/environments/${ENV}"
    local BACKEND_FILE="${ENV_DIR}/backend.hcl"

    # Capitalize environment name for display
    local ENV_DISPLAY=$(echo "${ENV}" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')

    if [ ! -d "$ENV_DIR" ]; then
        echo -e "${YELLOW}Warning: Environment directory not found: ${ENV_DIR}${NC}"
        return
    fi

    echo "Generating backend.hcl for ${ENV} environment..."

    cat > "$BACKEND_FILE" <<EOF
# Backend configuration for ${ENV_DISPLAY} Environment
# Auto-generated by generate-backend-configs.sh on $(date +"%Y-%m-%d %H:%M:%S")

bucket         = "${BUCKET_NAME}"
key            = "${ENV}/terraform.tfstate"
region         = "${REGION}"
dynamodb_table = "${TABLE_NAME}"
encrypt        = true
EOF

    echo -e "${GREEN}✓${NC} Created: ${BACKEND_FILE}"
}

# Generate backend configs for all environments
generate_backend_config "dev"
generate_backend_config "prod"

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Backend configs generated!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "You can now initialize each environment with:"
echo ""
echo "  cd environments/dev"
echo "  terraform init -backend-config=backend.hcl"
echo ""
echo "  cd environments/prod"
echo "  terraform init -backend-config=backend.hcl"
echo ""
echo -e "${YELLOW}Note: backend.hcl files are gitignored to allow per-developer configs${NC}"
